substitutions:
  name: "automower"
  friendlyName: "Husqvarna Automower 220AC"
  timezone: "Europe/Stockholm"
  rxpin: "GPIO3"
  txpin: "GPIO1"
  baud: "9600"
  device_password: !secret automower_password
  device_api_key: !secret automower_api_key
  
esphome:
  name: ${name}
  friendly_name: ${friendlyName}

time:
  - platform: homeassistant
    id: homeassistant_time
    timezone: ${timezone}

api:
  encryption:
    key: "${device_api_key}"

ota:
  - platform: esphome
    password: "${device_password}"

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password

  # Enable fallback hotspot (captive portal) in case wifi connection fails
  ap:
    ssid: "${friendlyName} Fallback Hotspot"
    password: !secret wifi_password

captive_portal:

external_components:
  - source: github://scanearth/esphome-hqam@main
    refresh: always

packages:
  remote_package:
    url: https://github.com/scanearth/esphome-hqam
    ref: main
    refresh: always
    files: [
        components/boards/d1_mini.yaml,
        components/confs/base.yaml,
        components/confs/button.yaml,
        components/confs/select.yaml,
        components/confs/sensor.yaml,
        components/confs/textsensor.yaml,
        components/confs/switch.yaml,
      ]
